name: Main Branch Workflow

on:
  schedule:
      - cron: '0 2 * * *'

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: build ADO pipeline scan plugin
        continue-on-error: true
        run: |
             npm i -g tfx-cli
             ./plugin-update.sh ${{ secrets.ADO_ORG }} ${{ secrets.ADO_TOKEN }}
      - name: commit back to repo
        run: |
             git config --global user.name 'julz0815'
             git config --global user.email 'j.totzek@gmail.com'
             git add -A
             git commit -am "New Plugin Version"
             git push --verbose