name: Main Branch Workflow

on:
  push:
    branches:
      - main
  schedule:
      - cron: '0 2 * * *'

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build ADO pipeline scan plugin
        run: |
             ./plugin-update.sh ${{ secrets.ADO_ORG }} ${{ secrets.ADO_TOKEN }}

