name: Main Branch Workflow

on:
  push:
    branches:
      - main
  schedule:
      - cron: '0 2 * * *'

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build ADO pipeline scan plugin
        run: |
             curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
             sudo apt-get install -y nodejs
             ./plugin-update.sh ${{ secrets.ADO_ORG }} ${{ secrets.ADO_TOKEN }} justBuildIt

