 name: Master Branch Workflow


on:
  push:
    branches: [ master ]
  schedule:
    - cron: '35 9 * * *'


 
 build-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: build ADO pipeline scna plugin
        run: |
          ./plugin-update.sh ${{ secrets.ADO_ORG }} ${{ secrets.ADO_TOKEN }}

